name: Notificar Nova Versão

on:
  release:
    types: [published]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Ler Lista de Emails
        id: read_emails
        run: |
          # Lê o ficheiro e junta os emails separados por vírgula
          EMAILS=$(paste -sd "," emails.txt)
          echo "lista=$EMAILS" >> $GITHUB_OUTPUT

      - name: Enviar E-mail de Notificação
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Nova Versão Disponível: ${{ github.event.release.tag_name }}"
          # Usa a saída do passo anterior
          to: ${{ steps.read_emails.outputs.lista }}
          from: "App Support <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            Olá!
            
            Uma nova versão do projeto foi lançada: ${{ github.event.release.tag_name }}
            
            Notas da Versão:
            ${{ github.event.release.body }}
            
            Para descarregar a versão mais recente diretamente, clique no link abaixo:
            ${{ github.event.release.html_url }}
